### ISSUE TITLE
Default data location

### ISSUE THREAD

**Issue by ra-one** [adswerve/target-bigquery#1]
There is slight inconsistency between the code and documentation

According to [Step 2: Configure](https://github.com/adswerve/target-bigquery#step-2-configure) in `README.md` the default data location is `EU`.

Per code it is `US` as in 

[__init__.py](https://github.com/adswerve/target-bigquery/blob/master/target_bigquery/__init__.py#L51)
[processhandler.py](https://github.com/adswerve/target-bigquery/blob/master/target_bigquery/processhandler.py#L80)

**Comment by zvizdo** [comment]
Thanks for flagging. We are in the process of updating the readme in a more comprehensive way, and we'll include this detail.

**Comment by RuslanBergenov** [comment]
@zvizdo, Issues 1, 5 and 6 are fixed here: https://github.com/adswerve/target-bigquery/tree/hotfix/issues1_5_6-documentation. Can you please QA?

**Comment by zvizdo** [comment]
@RuslanBergenov this mostly looks good.
Few things to change:

_1. Under Grant this service account access to the project, select Basic -> BigQuery Data Editor. Click Done_
We would want to give BigQuery Data Editor and BQ Job User as the min set of permissions. Data Editor allows to access (and change) the data, Job User gives permission to actually run a load or select job.

_2. Step 3_
Link to the sample config is invalid.

There's probably more things we can explain as part of the config part, but for now this is okay.

**Comment by RuslanBergenov** [comment]
Thank you for your feedback @zvizdo, fixed

**Comment by RuslanBergenov** [comment]
Happy Friday, I pushed another update to Target-BigQuery README. I added info about:

- partitioning
- clustering
- more info about config files
- Adswerve contact info (same as we used for [GA4 Measurement Protocol Python repository](https://github.com/adswerve/GA4-Measurement-Protocol-Python))

https://github.com/adswerve/target-bigquery/tree/hotfix/issues1_5_6-documentation

**Comment by RuslanBergenov** [comment]
Fixed, README updates merged into Master
