### ISSUE TITLE
Remove hard-coded FLOAT for numeric types

### ISSUE THREAD

**Issue by wolfadactyl** [adswerve/target-bigquery#11]
I mentioned this issue in the [RealSelf repo](https://github.com/RealSelf/target-bigquery/issues/40) but figured I'd post here as well in case there is more traction. At current it does not appear to be possible to have an output that uses numeric instead of float data types - this is ok for some applications but a critical bug for places where accuracy is important due to the nature of issues involving floating point precision. It would be great if it were possible to change to [using `NUMERIC` data types](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#numeric_types) in some way, although I'm not sure what all it would take to make that configurable.

**Comment by zvizdo** [comment]
Thank you for a great idea!
We have added this functionality to [this branch](https://github.com/adswerve/target-bigquery/tree/feature/decimal-type) and will be added to the next release.

Your JSON schema should be formatted like this:
`"deci": { "type": "string", "format": "bq-decimal" }`
