### ISSUE TITLE
Enable passing --tables file via config variable

### ISSUE THREAD

**Issue by dan-ladd** [adswerve/target-bigquery#15]
Hi Folks,

First off, thanks for maintaining this target. I've been using it as it's the default for [Meltano](https://meltano.com/plugins/loaders/bigquery.html).

One issue I've been having is using the partitioning and clustering feature. Meltano doesn't support tap or target specific cli arguments so I have no way to pass --tables. Discussed on the meltano slack here: https://meltano.slack.com/archives/CFG3C3C66/p1616601593113900

Can we pass the file through a config parameter? I will submit a PR for this.

Thanks!
Dan

**Comment by zvizdo** [comment]
Hello!

This seems like a great idea. I don't see any harm in having two ways of passing the --tables flag.
Internally we use the flag, but I see how it could be very useful for Meltano users.

Let us know when the PR is ready and we can get that merged in.

Thank you,
Anže

**Comment by dan-ladd** [comment]
All set now and ready to merge, thanks Anže!

**Comment by RuslanBergenov** [comment]
Hi Dan,

Anže approved these changes to be merged into master, your PR has been merged. 

Thank you for building this feature!
Ruslan
