### ISSUE TITLE
Authenticate without a private key file 

### ISSUE THREAD

**Issue by James-DBA-Anderson** [adswerve/target-bigquery#19]
Hi

I'm trying to use target-bigquery with Meltano on GKE that is running under a service account that has access to BigQuery. 

Your authentication instructions only mention using a private key file named client_secrets.json. 

My understanding is that Google client libraries will attempt to use the service account attached to resource that is running the code, in this case, that is a pod in GKE that is using the default node pool to use the cluster's service account. This is [Application Default Credentials](https://cloud.google.com/docs/authentication/production#best_practices_for_managing_credentials) (ADC).

So I should be able to target-bigquery on GKE without a client_credentials.json file but I get the the following error:

```
target-bigquery | Traceback (most recent call last):
target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/bin/target-bigquery", line 8, in <module>
target-bigquery |     sys.exit(main())
target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/target_bigquery/__init__.py", line 61, in main
target-bigquery |     client, dataset = ensure_dataset(project_id, dataset_id, location)
target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/target_bigquery/utils.py", line 28, in ensure_dataset
target-bigquery |     client = bigquery.Client(project=project_id, location=location)
target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/google/cloud/bigquery/client.py", line 179, in __init__
target-bigquery |     project=project, credentials=credentials, _http=_http
target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/google/cloud/client.py", line 320, in __init__
target-bigquery |     self, credentials=credentials, client_options=client_options, _http=_http
target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/google/cloud/client.py", line 178, in __init__
target-bigquery |     credentials, _ = google.auth.default(scopes=scopes)
target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/google/auth/_default.py", line 459, in default
target-bigquery |     credentials, project_id = checker()
target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/google/auth/_default.py", line 222, in _get_explicit_environ_credentials
target-bigquery |     os.environ[environment_vars.CREDENTIALS]
target-bigquery |   File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.6/site-packages/google/auth/_default.py", line 108, in load_credentials_from_file
target-bigquery |     "File {} was not found.".format(filename)
target-bigquery | google.auth.exceptions.DefaultCredentialsError: File /project/client_secrets.json was not found.
meltano         | Loading failed (1): google.auth.exceptions.DefaultCredentialsError: File /project/client_secrets.json was not found.
meltano         | ELT could not be completed: Loader failed
ELT could not be completed: Loader failed
```

Are you aware of authenticating without the key file being possible? It seems like it should work when reading the docs.

Thanks

**Comment by RuslanBergenov** [comment]
Hi @James-DBA-Anderson, the README part which talks about client_credentials.json file - this is more for testing locally on your laptop. We think it should run on GCP without client_credentials.json file. It's strange it fails. 

In the https://github.com/adswerve/target-bigquery/blob/master/target_bigquery/utils.py under ensure_dataset we are not using a key to authenticate

When you're running it on GKE, do you have a  GOOGLE_APPLICATION_CREDENTIALS env var with the value of /project/client_secrets.json? If yes, maybe remove it from GKE?

**Comment by James-DBA-Anderson** [comment]
I thought the same but running env from inside the container it doesn't return GOOGLE_APPLICATION_CREDENTIALS. 

This is strange, because looking into the error trace I can see that load_credentials_from_file in _get_explicit_environ_credentials in the [_default](https://google-auth.readthedocs.io/en/latest/_modules/google/auth/_default.html#default) module in Google's auth lib is being called. This only get's called if the env var GOOGLE_APPLICATION_CREDENTIALS  is not none.

So running env or printenv doesn't show it but the code is seeing it and it has the value /projects/client_secrets.json. I tried setting GOOGLE_APPLICATION_CREDENTIALS  to '' which it does see and obviously fails to load the file. It doesn't treat '' as the env var being empty.

GOOGLE_APPLICATION_CREDENTIALS  must be set in my environment at some point but I can't see it. Strange. Thanks for your help but I guess this is my problem.

**Comment by James-DBA-Anderson** [comment]
I could be clutching at straws here but does this [bug fix ](https://github.com/googleapis/google-auth-library-python/commit/c34452ef450c42cfef37a1b0c548bb422302dd5d) sound like it's to fix my issue to you?

I expect that latest version of the bigquery client will use the latest auth lib that has this fix.

 Are you planning a release with updated packages soon?

**Comment by RuslanBergenov** [comment]
Hi @James-DBA-Anderson, 

I'm not sure, but hopefully that bug fix resolves your issue. As you saw, it tackles GOOGLE_APPLICATION_CREDENTIALS and authentication.

We updated the dependencies in a dev branch, including google-cloud-bigquery (it was bumped from 2.20.0 to 2.24.0, which is the latest version). The CI/CD pipeline in our repo is still running, but looking good so far. 

I will need to check with our senior engineers before we do the new release. 

In the meantime, can you point your GKE application to a specific branch of our repo? If yes, please try this branch: https://github.com/adswerve/target-bigquery/tree/development-update-requirements

**Comment by RuslanBergenov** [comment]
@James-DBA-Anderson, let me know when you have a chance to test your application with this branch: https://github.com/adswerve/target-bigquery/tree/development-update-requirements

**Comment by James-DBA-Anderson** [comment]
Hi, @RuslanBergenov I did try your branch and I still get the same. Think I need to switch to something else. Thanks

**Comment by RuslanBergenov** [comment]
I'll close the issue for now, but we can reopen if there's anything else we can do to help you.

**Comment by RuslanBergenov** [comment]
I'll close the issue for now, but we can reopen if there's anything else we can do to help you.

**Comment by James-DBA-Anderson** [comment]
FYI I was trying to get your connector to work on GKE via Meltano. I have been able to get your connector to work on GKE without Meltano. I'll pick up with the Meltano guys to see what is happening. Thanks for looking.

**Comment by RuslanBergenov** [comment]
Hi James, glad to hear you have narrowed down the issue.

**Comment by James-DBA-Anderson** [comment]
Hi @RuslanBergenov, I have finally managed to solve my issue. When running target-bigquery via Meltano there is some default config for target-bigquery in their discovery.yml that creates the env var GOOGLE_APPLICATION_CREDENTIALS. Once I defined a namespace for my target-bigquery settings in my project's meltano.yml, I was able to overirde this behaviour. All is working now. Thanks for your help. You can close this issue now.

**Comment by RuslanBergenov** [comment]
Hi @James-DBA-Anderson, thank you for the information, glad to hear it's working.
