### ISSUE TITLE
replication_method: truncate, does not behave correctly

### ISSUE THREAD

**Issue by ra-one** [adswerve/target-bigquery#2]
When `replication_method` is set to `truncate`, it still appends data to the table.

As per [processhandler.py L152](https://github.com/adswerve/target-bigquery/blob/master/target_bigquery/processhandler.py#L152) the copy operation does not take into account `replication_method` and always `appends` the data.

**Comment by zvizdo** [comment]
The code reference is for the partial temp table load which technically doesn't matter if it appends or truncates.
The final table is generated via [this code](https://github.com/adswerve/target-bigquery/blob/master/target_bigquery/processhandler.py#L203) and it should respect the replication_method key.
However, we will double-check this behavior.

**Comment by jarobe42** [comment]
@zvizdo, if my reading of this is correct, this line in [processhandler.py L152](https://github.com/adswerve/target-bigquery/blob/master/target_bigquery/processhandler.py#L152) will always mean the tmp table is copied into the production table with an `append` WriteDisposition.

The code you linked to (https://github.com/adswerve/target-bigquery/blob/master/target_bigquery/processhandler.py#L203) is within the `_load_to_bq` method, which is called from `_do_temp_table_based_load`. This only loads the data into a temporary table. The temporary table is then copied into the production table with an Append, which would result in duplicate rows.

**Comment by zvizdo** [comment]
Yes, you are correct. I missed that when I responded the first time.
Should be easy to take care of. The solution in the meantime would be to use include metadata columns into the result, and so you can dedupe based on the ingestion time.

**Comment by zvizdo** [comment]
Fix implemented [here](https://github.com/adswerve/target-bigquery/tree/hotfix/issue2) based on @jarobe42 recommendation.
We have a few things in the works for the next release, so at this time we will hold off on merging to the master.
