### ISSUE TITLE
Target fails when receiving a SCHEMA with a property-less `object` node

### ISSUE THREAD

**Issue by aaronsteers** [adswerve/target-bigquery#20]
## Issue Description

The target crashes if the tap sends a SCHEMA containing a subnode that has type of `object` and no defined subproperties.

## Expected Behavior

It makes sense to fail if the top-level stream object has a fully-variant type declaration. For instance, if the stream `users` has zero properties, there's not enough information available to build a target table in bigquery. 

However, for subnodes having zero subproperties, there are at least two ways to handle these: (1) as a json-typed node or (2) as a string (rendered from `str(node)` for instance).

## Additional background

As noted in Slack threads (linked in below comment), tap-quickbooks from hotglue currently does send some sub-nodes without subproperty definitions. When paired with this target, the pipeline will fail.

**Comment by dan-ladd** [comment]
Slack threads: https://meltano.slack.com/archives/C01TCRBBJD7/p1629486263231400

https://meltano.slack.com/archives/C013EKWA2Q1/p1629150244061500

**Comment by RuslanBergenov** [comment]
Hi @aaronsteers and @dan-ladd, 

I'm having a hard time trying to join Meltano Slack workspace (maybe because I need an invitation(?) or maybe because it's Friday evening).

Can you please give me an example of input JSON schema / tap catalog file which is being passed into target-bigquery, which causes it to fail? Can you provide the entire JSON schema file, if possible (if it doesn't have any sensitive information).

**Comment by aaronsteers** [comment]
> Hi @aaronsteers and @dan-ladd, 
> 
> 1) I'm having a hard time trying to join Meltano Slack workspace (maybe because I need an invitation(?) or maybe because it's Friday evening). Can you send me an invitation please?
> 
> 2) Can you please give me an example of input JSON schema / tap catalog file which is being passed into target-bigquery, which causes it to fail? Can you provide the entire JSON schema file, if possible (if it doesn't have any sensitive information)?
> 
> 3. What error does target-bigquery give you? 

@RuslanBergenov Sorry about that! Here's the join link: https://join.slack.com/t/meltano/shared_invite/zt-obgpdeba-7yrqKhwyMBfdHDXsZY8G7Q

 I'm out for the day but myself or @dan-ladd or another team member can send more info Monday.

**Comment by RuslanBergenov** [comment]
@aaronsteers, great, thank you, I confirm that I was able to join Meltano Slack workspace. Have a nice weekend!

**Comment by RuslanBergenov** [comment]
@aaronsteers , @dan-ladd, regarding my second question above:

_Can you please give me an example of input JSON schema / tap catalog file which is being passed into target-bigquery, which causes it to fail? Can you provide the entire JSON schema file, if possible (if it doesn't have any sensitive information)?_

if it's easier, feel free to provide catalog file with only one stream, which causes the error.

**Comment by RuslanBergenov** [comment]
I did find a invoice_stream.json file someone attached to this discussion:

https://app.slack.com/client/TFG99TU9K/C013EKWA2Q1/thread/C013EKWA2Q1-1629150244.061500

I guess I could use that file to try to replicate your error, is that correct?

{
      "stream": "Invoice",
      "tap_stream_id": "Invoice",
      "schema": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "AllowIPNPayment": {
            "type": [
              "boolean",
              "null"
            ]
          },
          "AllowOnlinePayment": {
            "type": [
              "boolean",
              "null"
            ]
          },
          "AllowOnlineCreditCardPayment": {
            "type": [
              "boolean",
              "null"
            ]
          },

**Comment by RuslanBergenov** [comment]
@aaronsteers, I'll close this issue (the rationale is in the comment above).
