### ISSUE TITLE
Feature suggestions: Infer `DECIMAL` type from `multipleOf`

### ISSUE THREAD

**Issue by paultiplady** [adswerve/target-bigquery#22]
Currently there is some support for `bq-decimal` types, but it requires overriding the schema to use non-standard types.

https://github.com/adswerve/target-bigquery/issues/11

Looking at the output from `tap-mysql`, it seems that we could unambiguously identify `NUMERIC` / `DECIMAL` (same thing in BQ) by looking at the full schema entry:

```
          "amount": {
            "inclusion": "available",
            "multipleOf": 0.01,
            "type": [
              "null",
              "number"
            ]
          },
```

It seems that if we have a `type=number` that also specifies `multipleOf`, then you're dealing with a `DECIMAL` not a float.

The above came from a `` `amount` numeric(65, 2) NOT NULL`` column, so it seems that `tap-mysql` doesn't correctly propagate the digits part, which could in principle be used to infer `DECIMAL` vs. `BIGDECIMAL` in the BigQuery schema. But for small decimals perhaps it's possible to automatically infer the type more accurately.

(I don't know if the `multipleOf` schema is used more widely.)

**Comment by RuslanBergenov** [comment]
Sorry for late reply @paultiplady. We will discuss this and get back to you.

**Comment by paultiplady** [comment]
No rush! We have a fork that hardcodes a non-generic solution to this issue but would rather be following your repo.

**Comment by RuslanBergenov** [comment]
@paultiplady, we are okay with this change, thank you for your contribution. I merged your Pull Request into a dev branch. We'll test it more, make some tweaks, and do a code review, before we release it. 

cc @zvizdo

**Comment by RuslanBergenov** [comment]
We made some changes to the feature. [This branch](https://github.com/adswerve/target-bigquery/tree/feature/infer-decimal) is currently going through a code review.

**Comment by RuslanBergenov** [comment]
Thank you for your contribution @paultiplady, we have just released your feature.
