### ISSUE TITLE
Bump required version of setuptools to `57.5.0`

### ISSUE THREAD

**Issue by edgarrmondragon** [adswerve/target-bigquery#26]
It shouldn't introduce any breaking changes from the currently supported `57.4.x`.

**Comment by RuslanBergenov** [comment]
@edgarrmondragon, thank you for your suggestion. We have bumped `setuptools` to the latest version `60.3.1`, tested it and released it.

**Comment by edgarrmondragon** [comment]
Thank you @RuslanBergenov!
