### ISSUE TITLE
Empty schema {} causes validation failure

### ISSUE THREAD

**Issue by ra-one** [adswerve/target-bigquery#3]
Currently If the schema contains `empty schema {}` the validation fails.

```json
"properties": {
  "anyOf": [
    {
      "items": {
        "properties": {
          "name": { "type": [ "null", "string" ] },
          "value": { "type": [ "null", "string" ] }
        },
        "type": [ "null", "object" ]
      },
      "type": [ "null", "array" ]
    },
    {
      "properties": {},
      "type": ["null", "object"]
    }
  ]
}
```
In the code above `"properties": {}` will cause failure

**Comment by zvizdo** [comment]
@RuslanBergenov this might have been solved by your latest schema fixes.
As discussed, let's put a schema validation phase before converting to BQ schema.

**Comment by Jake8K** [comment]
This is not a bug. Catalog Files need to be completely and entirely defined.  BigQuery requires a properly defined schema to accept data and the only way to do that is to parse the catalog file into a BigQuery Schema object. The catalog files often have gaps, you’ll need to dig into the tap output or tap source API documentation  and properly define every field in the catalog. Make sure the data type is correct as well. Oftentimes these catalogs don’t switch timestamps to date-time. It’s frustrating, but in the end will lead to better data in your warehouse.
We're working on a feature to detect incomplete schemas in the catalog file at the start of a run.
