### ISSUE TITLE
Parametrize the granularity of BigQuery partitions 

### ISSUE THREAD

**Issue by VinceLegendre** [adswerve/target-bigquery#39]
Setting the granularity of partitions would be useful for a number of use cases, for example to avoid reaching the max number of partitions when syncing a table with a large history depth.

Since the table config JSON files already handle the choice of the `PARTITION BY`column, would it be possible to:

- add a `partition_by` parameter, taking a value among [`DAY`, `HOUR`, `MONTH`, `YEAR`]
- handle the value of this parameter rather than hard-setting `type_=bigquery.table.TimePartitioningType.DAY` (from [source](https://github.com/adswerve/target-bigquery/blob/master/target_bigquery/processhandler.py#L362))

Happy to work on a PR if you guys find the issue interesting!

**Comment by zvizdo** [comment]
Thank you for the suggestion. This is currently implemented in the branch linked to the issue.

This will likely be included in the next release.
Adding @RuslanBergenov for visibility.

**Comment by RuslanBergenov** [comment]
@VinceLegendre, @zvizdo, thank you for your contribution. Released.
