### ISSUE TITLE
Outputing empty state instead of the previous state when a tap fails

### ISSUE THREAD

**Issue by Muriloo** [adswerve/target-bigquery#9]
**Issue:**
When running this target together with a tap, if the tap fails, this target is outputting an empty state. 

**Scenario where the issue was found:**
By running an incremental elt job using Meltano, when a tap fails, the next run of that tap is not being able to use the previous state, because this integration is pushing a state before receiving the state from meltano.
When the next run is triggered, Meltano sees an empty state and reset to default start_date, instead of using the state of the previous job.

Probably the issue is related to pushing a state before actually receiving one, [see here](https://github.com/adswerve/target-bigquery/blob/master/target_bigquery/process.py#L22).
[See this Meltano's slack thread for more details](https://meltano.slack.com/archives/CFG3C3C66/p1614621579049600)

**Comment by zvizdo** [comment]
Apologies for the delay on this.
You have correctly identified the issue. This is solvable by setting -s (--state) flag on target-bigquery that points to the same state that is being passed to the tap. That way that initial state emit will not be empty.

However, I think it's reasonable to say that if the -s flag is not set, there should be nothing emitted until the actual state comes from the tap. We added [this fix to this branch](https://github.com/adswerve/target-bigquery/tree/hotfix/issue9) and will be part of the next release.

Thank you!

**Comment by DouweM** [comment]
@zvizdo When are you expecting to release that bugfix? Another Meltano user just ran into the same issue :)

**Comment by RuslanBergenov** [comment]
Hi @DouweM, 

We are working on the new release. We need to:
1) consolidate changes in our development branches
2) run integrated tests
3) fix the bugs we find

We are not 100% sure on the timeline yet, it depends on our general workload and how many bugs we find during our integrated tests.

We hope to issue our next release, which will include the fix described in this thread, by end of this quarter (end of June).

**Comment by RuslanBergenov** [comment]
Hi @DouweM,

We are very close to releasing a new version of target-bigquery. Heads up: we might experience a one week delay. We plan to release around July 7-10. I apologize for the delay. We are currently improving tests, documentation and doing some refactoring. After that, we'll do a 2nd round of QA.

**Comment by DouweM** [comment]
@RuslanBergenov Awesome, thanks for the update!

**Comment by RuslanBergenov** [comment]
@DouweM, we have published a new release. Thank you for you patience.

**Comment by DouweM** [comment]
@RuslanBergenov Thanks a lot!
